//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.05 at 04:54:04 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.szboc.cn/projects/open/platform/communication/logger", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.szboc.platform.component.communication.logger.config.jaxb;
